language: cpp

compiler:
- clang
- gcc

env:
  global:
    - CHANGED_FOLDERS=

#before_install:

#install:

#before_script:

script:
- echo "git diff --name-only HEAD `git rev-parse origin/master`"

#after_script:
